android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
android.aapt2FromMavenOverride=C:\\Users\\munya\\AppData\\Local\\Android\\Sdk\\build-tools\\36.0.0\\aapt2.exe
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
